Fix gh command not found issue

diff --git a/developer-hub/pruner-job.yaml b/developer-hub/pruner-job.yaml
--- a/developer-hub/pruner-job.yaml
+++ b/developer-hub/pruner-job.yaml
@@ -41,7 +41,6 @@ spec:
                     creation_sec=$(date -u -d "${creation_ts}" +"%s" 2>/dev/null || echo 0)
 
                     age=$(( (NOW - creation_sec) / 60 ))
-                    echo $age
                     if [ "$age" -gt 3600 ]; then
                       echo "Deleting Application: $name (age: ${age}m)"
                       kubectl patch app $name  -p '{"metadata": {"finalizers": ["resources-finalizer.argocd.argoproj.io"]}}' --type merge -n $NAMESPACE
@@ -54,10 +53,20 @@ spec:
                       full_gitops_repo="$GH_ORG/$gitops_repo_name"
 
                       echo "Deleting GitHub repo: $full_app_repo"
-                      gh repo delete "$full_app_repo" --yes || echo "Failed to delete GitHub repo: $full_app_repo"
+                      curl -s -o /dev/null -w "%{http_code}" -X DELETE \
+                      -H "Authorization: token $GH_TOKEN" \
+                      -H "Accept: application/vnd.github+json" \
+                      "https://api.github.com/repos/$full_app_repo" | grep -q "204" \
+                      && echo "Deleted $full_app_repo" \
+                      || echo "Failed to delete $full_app_repo"
 
                       echo "Deleting GitHub repo: $full_gitops_repo"
-                      gh repo delete "$full_gitops_repo" --yes || echo "Failed to delete GitHub repo: $full_gitops_repo"
+                      curl -s -o /dev/null -w "%{http_code}" -X DELETE \
+                      -H "Authorization: token $GH_TOKEN" \
+                      -H "Accept: application/vnd.github+json" \
+                      "https://api.github.com/repos/$full_gitops_repo" | grep -q "204" \
+                      && echo "Deleted $full_gitops_repo" \
+                      || echo "Failed to delete $full_gitops_repo"
                     else
                       echo "found application $name. Age: $age m - skipping"
                     fi
