Add message when skipping application

diff --git a/developer-hub/pruner-job.yaml b/developer-hub/pruner-job.yaml
--- a/developer-hub/pruner-job.yaml
+++ b/developer-hub/pruner-job.yaml
@@ -36,28 +36,30 @@ spec:
                   NOW=$(date +%s)
 
                   kubectl get applications.argoproj.io -n "$NAMESPACE" -l "$LABEL_SELECTOR" -o json | jq -c '.items[]' | while read -r app; do
-                      name=$(echo "$app" | jq -r '.metadata.name')
-                      creation_ts=$(echo "$app" | jq -r '.metadata.creationTimestamp')
-                      creation_sec=$(date -u -d "${creation_ts}" +"%s" 2>/dev/null || echo 0)
+                    name=$(echo "$app" | jq -r '.metadata.name')
+                    creation_ts=$(echo "$app" | jq -r '.metadata.creationTimestamp')
+                    creation_sec=$(date -u -d "${creation_ts}" +"%s" 2>/dev/null || echo 0)
 
-                      age=$(( (NOW - creation_sec) / 60 ))
-                      echo $age
-                      if [ "$age" -gt 3600 ]; then
-                          echo "Deleting Application: $name (age: ${age}m)"
-                          kubectl patch app $name  -p '{"metadata": {"finalizers": ["resources-finalizer.argocd.argoproj.io"]}}' --type merge -n $NAMESPACE
-                          kubectl delete app $name -n $NAMESPACE
+                    age=$(( (NOW - creation_sec) / 60 ))
+                    echo $age
+                    if [ "$age" -gt 3600 ]; then
+                      echo "Deleting Application: $name (age: ${age}m)"
+                      kubectl patch app $name  -p '{"metadata": {"finalizers": ["resources-finalizer.argocd.argoproj.io"]}}' --type merge -n $NAMESPACE
+                      kubectl delete app $name -n $NAMESPACE
 
-                          app_repo_name="${name%-app-of-apps}"
-                          full_app_repo="$GH_ORG/$app_repo_name"
+                      app_repo_name="${name%-app-of-apps}"
+                      full_app_repo="$GH_ORG/$app_repo_name"
 
-                          gitops_repo_name="${name}-gitops"
-                          full_gitops_repo="$GH_ORG/$gitops_repo_name"
+                      gitops_repo_name="${name}-gitops"
+                      full_gitops_repo="$GH_ORG/$gitops_repo_name"
 
-                          echo "Deleting GitHub repo: $full_app_repo"
-                          gh repo delete "$full_app_repo" --yes || echo "Failed to delete GitHub repo: $full_app_repo"
+                      echo "Deleting GitHub repo: $full_app_repo"
+                      gh repo delete "$full_app_repo" --yes || echo "Failed to delete GitHub repo: $full_app_repo"
 
-                          echo "Deleting GitHub repo: $full_gitops_repo"
-                          gh repo delete "$full_gitops_repo" --yes || echo "Failed to delete GitHub repo: $full_gitops_repo"
-                      fi
-                      sleep 2
+                      echo "Deleting GitHub repo: $full_gitops_repo"
+                      gh repo delete "$full_gitops_repo" --yes || echo "Failed to delete GitHub repo: $full_gitops_repo"
+                    else
+                      echo "found application $name. Age: $age m - skipping"
+                    fi
+                    sleep 2
                   done
